#!/bin/bash
# run: $HOME/work/deezer-cli/deezer status

#### Set this occording to your pinned tab settings
tab_number=2
####

path_to_queue_header='$("#panel-queuelist > div > h3").text()'

function run_javascript() {
    osascript -e "
    tell application \"Safari\"
        set playScript to \""$1\""
        do JavaScript playScript in tab $tab_number of first window
    end tell
"
}

function queue() {
    (>&2 echo "Not yet working")
    run_javascript $path_to_queue_header
}

function title() {
    run_javascript "document.title"
}

function goto() {
    url="$1"
    osascript -e "
    tell application \"Safari\"
        set playScript to \"window.location.href = '$url'\"
        do JavaScript playScript in tab $tab_number of first window
    end tell
    "
}

function activate() {
    osascript -e "
        tell front window of application \"Safari\"
            set current tab to tab $tab_number
        end tell
    "
}

function next() {
    run_javascript "document.getElementsByClassName('control')[0].click();"
}

function playpause() {
    run_javascript "document.getElementsByClassName('control')[1].click();"
}

function next() {
    run_javascript "document.getElementsByClassName('control')[2].click();"
}

function status() {
    run_javascript "document.getElementsByClassName('control')[1].title;" |
        sed 's/Play/◼/g' | sed 's/Pause/▶/g'
}

function play() {
    playpause
}

function pause() {
    playpause
}


function track() {
    title | awk -F" - " '{print $2 " - " $1}'
}

function usage() {
    echo """usage: $0 [--help] <command>

Control Playback:

play        play track
pause       pause track
next        play next track
prev        play previous track

Information:

track       get title of track
status      show playback status

Control Deezer Window:

title       get title of Deezer window
goto        change url of Deezer window
activate    activate window if Deezer is not loaded yet. Will be run at every start.

Help:

usage       this message
"""
}

status=$(status)
if [[ "$status" == "" ]];then
  (>&2 echo "Activating $tab_number because window was inactive")
  activate
  sleep 5s
fi

case $1 in
    track)                  $1
                            ;;
    goto)                   $1 $2
                            ;;
    activate)               $1
                            ;;
    title)                  $1
                            ;;
    pause)                  $1
                            ;;
    play)                   $1
                            ;;
    queue)                  $1
                            ;;
    next)                   $1
                            ;;
    status)                 $1
                            ;;
    -h | --help )           usage
                            exit
                            ;;
    * )                     usage
                            exit 1
esac

